# Generated by Django 3.2.5 on 2021-08-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='owner',
        ),
    ]
